# Generated by Django 3.0.5 on 2020-04-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2, verbose_name='DDD')),
                ('number', models.CharField(max_length=11, verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Phone', verbose_name='Telefone')),
            ],
        ),
    ]
