# Generated by Django 3.0.5 on 2020-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
    ]
