# Generated by Django 3.0.5 on 2020-04-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200430_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='ddi',
        ),
    ]
