# Generated by Django 3.0.5 on 2020-04-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_phone_ddi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ddi',
            field=models.CharField(blank=True, max_length=2, verbose_name='DDI'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Número'),
        ),
    ]
