# Generated by Django 3.0.5 on 2020-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200430_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ddi',
            field=models.CharField(blank=True, default=55, max_length=2, verbose_name='DDI'),
        ),
    ]
