# Generated by Django 3.0.5 on 2020-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200504_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sobre'),
        ),
    ]
