# Generated by Django 3.0.5 on 2020-04-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200430_0943'),
        ('customers', '0004_auto_20200430_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.ForeignKey(blank=True, default=999999999, on_delete=django.db.models.deletion.CASCADE, to='contacts.Phone', verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
