# Generated by Django 3.0.5 on 2020-04-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_phone_ddi'),
        ('customers', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='contacts.Phone', verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
