# Generated by Django 3.0.5 on 2020-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended',
            field=models.CharField(default=1, max_length=150, verbose_name='Atendido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='topic',
            field=models.CharField(max_length=300, verbose_name='Assunto'),
        ),
    ]
